name: Check Package

on: push

jobs:
  check-package:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Check package install
        run: pip install .
      - name: Check tests
        run: |
          pip install pytest
          pytest
      - name: Check package build
        run: |
          python -m pip install --upgrade pip
          pip install build
          python -m build
