name: Dev workflow - check build and run tests
on: push

jobs:
  check-install:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: install package
        run: pip install .
  check-tests:
    needs: check-install
    runs-on: ubuntu-latest
    steps:
      - name: install pytest
        run: pip install pytest
      - name: run pytest
        run: pytest
